/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifce.telas;

import javax.swing.JOptionPane;
import java.sql.*;
import com.br.ifce.dal.Conexao;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Usuario
 */
public class TelaMaisInformacoes extends javax.swing.JFrame {

    Connection conexao = null;
PreparedStatement pst = null;
ResultSet rs = null; //exibe o resultado da conexão
    
    /**
     * Creates new form TelaMaisInformacoes
     */
    public TelaMaisInformacoes() {
        initComponents();
        conexao = Conexao.conector();
    }

        private void adicionarNota(){
String sql ="INSERT INTO disciplinas2 (ID, aluno, Disciplina, professor, nota1, nota2, nota3, faltas) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
try {
pst=conexao.prepareStatement(sql);
pst.setString(1,txtID.getText());
pst.setString(2,txtAluno.getText());
pst.setString(3,txtDisciplina.getText());
pst.setString(4,txtProfessor.getText());
pst.setString(5,txtNota1.getText());
pst.setString(6,txtNota2.getText());
pst.setString(7,txtNota3.getText());
pst.setString(8, txtFaltas.getText());
int adicionado = pst.executeUpdate();
if(adicionado >0){
JOptionPane.showMessageDialog(null,"Aluno cadastrado com sucesso");
txtID.setText(null);
txtAluno.setText(null);
txtDisciplina.setText(null);
txtProfessor.setText(null);
txtNota1.setText(null);
txtNota2.setText(null);
txtNota3.setText(null);
txtFaltas.setText(null);
}
} catch (Exception e) {
JOptionPane.showMessageDialog(null, e);
}
}
    
   private void consultarNotas(){
    String sql ="select * from disciplinas2 where ID=?";
    try {
    pst=conexao.prepareStatement(sql);
    pst.setString(1,txtID.getText());
    rs=pst.executeQuery();
    if (rs.next()) {
    txtAluno.setText(rs.getString(2));
    txtDisciplina.setText(rs.getString(3));
    txtProfessor.setText(rs.getString(4));
    txtNota1.setText(rs.getString(5));
    txtNota2.setText(rs.getString(6));
    txtNota3.setText(rs.getString(7));
    txtFaltas.setText(rs.getString(8));
    } else {
    JOptionPane.showMessageDialog(null,"Aluno não cadastrado");
    txtAluno.setText(null);
    txtDisciplina.setText(null);
    txtProfessor.setText(null);
    txtNota1.setText(null);
    txtNota2.setText(null);
    txtNota3.setText(null);
    txtFaltas.setText(null);
    }
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null,e);
    }
    }
    
   private void removerNota(){
int confirma=JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover estas informações?","Atenção", JOptionPane.YES_NO_OPTION);
if(confirma==JOptionPane.YES_OPTION){
String sql="delete from disciplinas2 where ID=?";
try {
pst=conexao.prepareStatement(sql);
pst.setString(1,txtID.getText());
int apagado = pst.executeUpdate();
if (apagado>0) {
JOptionPane.showMessageDialog(null,"Informações removidas com sucesso");
}
} catch (Exception e) {
JOptionPane.showMessageDialog(null, e);
}
}
}
   
   private void alterarNota(){
String sql ="update disciplinas2 set aluno=?, Disciplina=?, professor=?, nota1=?, nota2=?, nota3=?, faltas=? where ID=?";
try {
pst=conexao.prepareStatement(sql);
pst.setString(1,txtID.getText());
pst.setString(2,txtAluno.getText());
pst.setString(3,txtDisciplina.getText());
pst.setString(4,txtProfessor.getText());
pst.setString(5,txtNota1.getText());
pst.setString(6,txtNota2.getText());
pst.setString(7,txtNota3.getText());
pst.setString(8, txtFaltas.getText());
int adicionado = pst.executeUpdate();
if(adicionado >0){
JOptionPane.showMessageDialog(null,"Nota alterada com sucesso");
txtID.setText(null);
txtAluno.setText(null);
txtDisciplina.setText(null);
txtProfessor.setText(null);
txtNota1.setText(null);
txtNota2.setText(null);
txtNota3.setText(null);
txtFaltas.setText(null);
}
} catch (Exception e) {
JOptionPane.showMessageDialog(null, e);
}
}
   
   private void pesquisar_nota(){
String sql= "select     d.id, a.nome, d.disciplina,  p.nome,  d.nota1,  d.nota2,  d.nota3, d.faltas from disciplinas2 as d inner join alunos as a on d.aluno = a.matrícula inner join professores as p on d.professor = p.id Where Disciplina like ?";
try {
pst = conexao.prepareStatement(sql);
pst.setString(1, txtNotaPesquisar.getText() + "%");
rs=pst.executeQuery();
tabNotas.setModel(DbUtils.resultSetToTableModel(rs));
} catch (Exception e) {
JOptionPane.showMessageDialog(null, e);
}
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabNotas = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        txtAluno = new javax.swing.JTextField();
        txtDisciplina = new javax.swing.JTextField();
        txtProfessor = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        txtFaltas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNotaPesquisar = new javax.swing.JTextField();
        btnAddNota = new javax.swing.JButton();
        btnPesqNota = new javax.swing.JButton();
        btnAttNota = new javax.swing.JButton();
        btnDeleteNota = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mais informações");
        setName("Mais informações"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(42, 48, 56));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(109, 203, 230));
        jLabel1.setText("MAIS INFORMAÇÕES");

        tabNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabNotas);

        btnVoltar.setBackground(new java.awt.Color(109, 203, 230));
        btnVoltar.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlunoActionPerformed(evt);
            }
        });

        txtDisciplina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisciplinaActionPerformed(evt);
            }
        });

        txtProfessor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorActionPerformed(evt);
            }
        });

        txtNota2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2ActionPerformed(evt);
            }
        });

        txtNota3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota3ActionPerformed(evt);
            }
        });

        txtFaltas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaltasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 203, 230));
        jLabel2.setText("Disciplina");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(109, 203, 230));
        jLabel3.setText("Professor");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(109, 203, 230));
        jLabel4.setText("Aluno");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(109, 203, 230));
        jLabel5.setText("Nota 1");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(109, 203, 230));
        jLabel6.setText("Nota 2");

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(109, 203, 230));
        jLabel7.setText("Nota 3");

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(109, 203, 230));
        jLabel8.setText("Faltas");

        txtNota1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(109, 203, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(460, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(109, 203, 230));
        jLabel9.setText("Pesquisa");

        txtNotaPesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtNotaPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNotaPesquisarKeyReleased(evt);
            }
        });

        btnAddNota.setBackground(new java.awt.Color(109, 203, 230));
        btnAddNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifce/icones/addDisc.png"))); // NOI18N
        btnAddNota.setToolTipText("Adicionar nota");
        btnAddNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNotaActionPerformed(evt);
            }
        });

        btnPesqNota.setBackground(new java.awt.Color(109, 203, 230));
        btnPesqNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifce/icones/pesqDisc.png"))); // NOI18N
        btnPesqNota.setToolTipText("Consultar nota");
        btnPesqNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqNotaActionPerformed(evt);
            }
        });

        btnAttNota.setBackground(new java.awt.Color(109, 203, 230));
        btnAttNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifce/icones/attDisc.png"))); // NOI18N
        btnAttNota.setToolTipText("Atualizar nota");
        btnAttNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttNotaActionPerformed(evt);
            }
        });

        btnDeleteNota.setBackground(new java.awt.Color(109, 203, 230));
        btnDeleteNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifce/icones/removerDisc.png"))); // NOI18N
        btnDeleteNota.setToolTipText("Excluir nota");
        btnDeleteNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNotaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(109, 203, 230));
        jLabel10.setText("ID");

        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(109, 203, 230)));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(txtNotaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnAddNota)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPesqNota)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAttNota)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDeleteNota))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNotaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesqNota, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddNota, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAttNota, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteNota, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNotaActionPerformed
           removerNota();
    }//GEN-LAST:event_btnDeleteNotaActionPerformed

    private void btnAttNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttNotaActionPerformed
           alterarNota();
    }//GEN-LAST:event_btnAttNotaActionPerformed

    private void btnPesqNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqNotaActionPerformed
           consultarNotas();
    }//GEN-LAST:event_btnPesqNotaActionPerformed

    private void btnAddNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNotaActionPerformed
           adicionarNota();
    }//GEN-LAST:event_btnAddNotaActionPerformed

    private void txtNotaPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNotaPesquisarKeyReleased
           pesquisar_nota();
    }//GEN-LAST:event_txtNotaPesquisarKeyReleased

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void txtFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaltasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaltasActionPerformed

    private void txtNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota3ActionPerformed

    private void txtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2ActionPerformed

    private void txtProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorActionPerformed

    private void txtDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisciplinaActionPerformed

    private void txtAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlunoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaAlunos inicial = new TelaAlunos();
        inicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMaisInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMaisInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMaisInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMaisInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMaisInformacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNota;
    private javax.swing.JButton btnAttNota;
    private javax.swing.JButton btnDeleteNota;
    private javax.swing.JButton btnPesqNota;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabNotas;
    private javax.swing.JTextField txtAluno;
    private javax.swing.JTextField txtDisciplina;
    private javax.swing.JTextField txtFaltas;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNotaPesquisar;
    private javax.swing.JTextField txtProfessor;
    // End of variables declaration//GEN-END:variables
}
